# AudioLDM data preprocessing config
# ⚠️ Notes:
# - Keep variable names consistent with the code (e.g., sampling_rate → self.sampling_rate)
# - Use integers or floats for numerical values
# - Avoid duplicate keys (last value will overwrite)
# - Ensure new variables are supported in the code
# - Code may override values via kwargs (e.g., sampling_rate=44100)

repo_id: "cvssp/audioldm"
precision: "high"
preprocessing:
  audio:
    sampling_rate: 16000
    duration: 10.24
    max_wav_value: 32768.0
  stft:
    n_fft: 1024             # filter_length
    win_length: 1024
    hop_length: 160
    stft_pad_size: 432      # (win_length - hop_length) // 2
  mel:
    mel_bins: 64
    mel_fmin: 0
    mel_fmax: 8000
shape:
  n_freq_bins: 513          # n_fft // 2 + 1
  n_time_frames: 1024       # (sample_length + 2 * stft_pad_size - win_length) // hop_length + 1
  sample_length: 163840     # sampling_rate * duration
