# DGMO pipeline config
# ⚠️ Notes:
# - Keep variable names consistent with the code (e.g., learning_rate → self.learning_rate)
# - Use integers or floats for numerical values
# - Avoid duplicate keys (last value will overwrite)
# - Ensure new variables are supported in the code
# - Code may override values via kwargs (e.g., sampling_rate=44100)

# AudioLDM data preprocessing config
ldm_config_path: "./configs/audioldm.yaml"

# learning_rate: 0.005

# ddim_batch: 2
# num_splits: 1

# iteration: 3
# epochs: 300
# noise_level: 0.6
# ddim_steps: 25
# guidance_scale: 2.5

# masking_mode: "basic"  # "basic" or "joint"

learning_rate: 0.001

ddim_batch: 4
num_splits: 1  # 몇번 쪼개서 할건지

iteration: 1
epochs: 300
noise_level: 0.7
ddim_steps: 25
guidance_scale: 7

masking_mode: "basic"  # "basic" or "joint"
