# DGMO pipeline config
# ⚠️ Notes:
# - Keep variable names consistent with the code (e.g., learning_rate → self.learning_rate)
# - Use integers or floats for numerical values
# - Avoid duplicate keys (last value will overwrite)
# - Ensure new variables are supported in the code
# - Code may override values via kwargs (e.g., sampling_rate=44100)

# AudioLDM data preprocessing config
ldm_config_path: "./configs/audioldm.yaml"

learning_rate: 0.01

ddim_batchsize: 4
batch_split: 1

iteration: 3
epochs: 100
noise_level: 1.0
ddim_steps: 100
guidance_scale: 2.5



